### ISSUE TITLE
dev sites cannot have their own repo

### ISSUE THREAD

**Issue by trebitzki** [creativecoder/wordpress-local-dev#2]
Not sure if I'm missing something here. I set up the local dev system and it's running fine. Now I'd like to create a git repo for my dev site, call it example.dev. Git Tower says: "The path belongs to an existing Git Repository!"

Now what? I've got a local WP dev system and can't use versioning on the sites??

I'd appreciate your clearing this up; for me it's a show stopper.

**Comment by trebitzki** [comment]
I ended up removing the wp-sites repo and creating a new wordpress remote clone in the same place:

```
$ cd ~/Sites/wp-sites
$ rm -rf .git
$ rm -rf .gitmodules
$ rm -rf wordpress
$ git clone https://github.com/WordPress/WordPress wordpress
```

Works the same as before; I can still `git pull` wordpress and have my dev site repos.

**Comment by creativecoder** [comment]
You got it. This repo is meant only to be an example of how to set up this system. Then you create your own git repos within each folder per site. Thanks for inquring. I've updated the readme to clarify this.
